name: spark_rest
description: A blazing-fast, single instance, sessionless RESTful API for Dart
version: 0.3.0
repository: https://github.com/xNovo3000/spark_rest

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:

dev_dependencies:
  test: ^1.17.10
